// Generated by tools/signature/build_signature.py. Do not edit.
// Seconds, matching the keyframes baked into the animated SVG.

export const signatureTiming = {
  /** Calm black before the first stroke (s5.7). */
  startDelay: 0.12,
  /** The signature is complete at this point. */
  draw: 2.44,
  /** Completed signature holds until here, then the intro fades. */
  hold: 2.6,
  /** Stroke group start times, for anything that needs to follow along. */
  groups: [
    { name: "A", startSeconds: 0.12 },
    { name: "crossbar", startSeconds: 0.3443 },
    { name: "bdul", startSeconds: 0.569 },
    { name: "m", startSeconds: 1.4843 },
    { name: "oiz", startSeconds: 1.736 },
    { name: "idot", startSeconds: 2.232 },
    { name: "underline", startSeconds: 2.3016 },
  ],
} as const;
