"""Original procedural 3D avatar, created for Abdul Moiz. Blender 4.5+.
Run: blender -b --python build_avatar.py -- <output-root>
No web application is generated by this script.
"""
import bpy, math, json, sys, random
from mathutils import Vector
from pathlib import Path

ROOT = Path(sys.argv[sys.argv.index('--')+1]) if '--' in sys.argv else Path(__file__).resolve().parents[1]
OUT = ROOT / 'avatar'
OUT.mkdir(parents=True, exist_ok=True)
random.seed(17)
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)

def lin(v):
    return v/12.92 if v <= .04045 else ((v+.055)/1.055)**2.4
def rgb(h):
    h=h.lstrip('#'); return tuple(lin(int(h[i:i+2],16)/255) for i in (0,2,4))
def material(name, color, rough=.45, metal=0.0, subsurface=0.0):
    m=bpy.data.materials.new(name); m.use_nodes=True
    p=m.node_tree.nodes.get('Principled BSDF')
    p.inputs['Base Color'].default_value=(*rgb(color),1)
    p.inputs['Roughness'].default_value=rough
    p.inputs['Metallic'].default_value=metal
    p.inputs['Subsurface Weight'].default_value=subsurface
    m.diffuse_color=(*rgb(color),1)
    return m

skin=material('Skin | warm porcelain clay','#C98D68',.43,subsurface=.07)
skin_shadow=material('Ear inner / eyelid','#A9674F',.5)
lip=material('Lip | muted terracotta','#955B4E',.5)
mouth=material('Smile line','#55392F',.6)
hair=material('Hair | espresso','#211B19',.32)
hair_high=material('Hair | sculpted ridges','#302522',.37)
white=material('Eyes | ivory','#F1E6D8',.24)
iris=material('Iris | chestnut','#62432F',.27)
pupil=material('Pupil','#11100F',.21)
glint=material('Eye catchlight','#FFF9E9',.1)
frames=material('Frames | smoked warm metal','#7F7568',.27,.72)
jacket=material('Jacket | charcoal','#292827',.53)
rib=material('Ribbed collar and hem','#191817',.65)
orange=material('T-shirt | signal orange','#F9542A',.61)
rust=material('Jacket piping | rust','#87392A',.5)
amber=material('Zipper / badge','#D9835A',.38,.35)

parts=[]
def finish(o,name,mat,bone='Chest',smooth=True):
    o.name=name
    if mat: o.data.materials.append(mat)
    if o.type=='MESH' and smooth:
        for p in o.data.polygons:p.use_smooth=True
    o['bind_bone']=bone
    parts.append(o)
    return o
def sphere(name,loc,scale,mat,bone='Head',segments=32,rings=20):
    bpy.ops.mesh.primitive_uv_sphere_add(segments=segments,ring_count=rings,location=loc)
    o=bpy.context.object;o.scale=scale
    bpy.ops.object.transform_apply(location=False,rotation=False,scale=True)
    return finish(o,name,mat,bone)
def mesh(name,verts,faces,mat,bone='Head',sub=0):
    d=bpy.data.meshes.new(name);d.from_pydata(verts,[],faces);d.update()
    o=bpy.data.objects.new(name,d);bpy.context.collection.objects.link(o)
    finish(o,name,mat,bone)
    if sub:
        mod=o.modifiers.new('Soft sculpt subdivision','SUBSURF');mod.levels=sub;mod.render_levels=sub
    return o
def curve(name,pts,radius,mat,bone='Head',closed=False,res=3):
    d=bpy.data.curves.new(name,'CURVE');d.dimensions='3D';d.resolution_u=res
    d.bevel_depth=radius;d.bevel_resolution=3
    s=d.splines.new('BEZIER');s.bezier_points.add(len(pts)-1)
    for b,p in zip(s.bezier_points,pts):
        b.co=p[:3];b.handle_left_type='AUTO';b.handle_right_type='AUTO'
        if len(p)>3:b.radius=p[3]
    s.use_cyclic_u=closed
    o=bpy.data.objects.new(name,d);bpy.context.collection.objects.link(o)
    return finish(o,name,mat,bone)
def loft(name,rows,mat,bone='Chest',n=64,sub=1):
    vs=[]
    for z,rx,ry,yoff in rows:
        for i in range(n):
            a=2*math.pi*i/n
            vs.append((rx*math.cos(a),yoff+ry*math.sin(a),z))
    fs=[]
    for j in range(len(rows)-1):
        for i in range(n):a=j*n+i;b=j*n+(i+1)%n;fs.append((a,b,b+n,a+n))
    fs.append(tuple(range(n-1,-1,-1)));fs.append(tuple((len(rows)-1)*n+i for i in range(n)))
    return mesh(name,vs,fs,mat,bone,sub)
def capsule(name,a,b,radii,mat,bone='Chest'):
    a,b=Vector(a),Vector(b);o=sphere(name,(a+b)*.5,(*radii,(b-a).length*.62),mat,bone)
    o.rotation_mode='QUATERNION';o.rotation_quaternion=(b-a).to_track_quat('Z','Y')
    return o

# A coherent tailored bust. Flat bottom gives a clean crop in the future hero.
loft('Bomber jacket / torso',[(.52,.48,.23,.025),(.54,.52,.25,.025),(.67,.55,.26,.02),
     (1.05,.59,.29,.025),(1.43,.63,.27,.05),(1.60,.54,.24,.06),(1.70,.31,.19,.045),
     (1.73,.23,.165,.04)],jacket)
loft('Hem band',[(.51,.48,.23,.025),(.535,.515,.244,.025),(.605,.53,.25,.025)],rib)
for side in (-1,1):
    capsule(('L' if side<0 else 'R')+' upper sleeve',(side*.47,.04,1.57),(side*.72,.03,1.14),(.215,.215),jacket)
    capsule(('L' if side<0 else 'R')+' lower sleeve',(side*.72,.035,1.15),(side*.67,-.01,.58),(.18,.19),jacket)
    curve('Sleeve seam',[(side*.58,-.12,1.63),(side*.71,-.13,1.42),(side*.805,-.09,1.13)],.006,rust,'Chest')
    curve('Cuff piping',[(side*.54,-.15,.63),(side*.66,-.20,.61),(side*.78,-.12,.62)],.009,rib,'Chest')

# An orange inner top visible in the open neck, bordered by a raised jacket collar.
loft('Inner orange top',[(1.28,.21,.207,-.022),(1.48,.23,.207,-.018),(1.66,.245,.183,.004),
     (1.745,.192,.155,.011)],orange,sub=1)
loft('Neck',[(1.69,.166,.149,.025),(1.77,.16,.153,.025),(1.96,.157,.16,.028),(2.03,.19,.17,.02)],skin,'Head',sub=1)
for side in (-1,1):
    curve('Raised bomber collar',[(0,-.205,1.48),(side*.15,-.21,1.53),(side*.249,-.145,1.69),
          (side*.205,.027,1.765),(side*.13,.152,1.74)],.028,rib,'Chest')
    curve('Collar stitch',[(side*.038,-.225,1.49),(side*.15,-.232,1.545),(side*.243,-.175,1.665)],.0045,amber,'Chest')
curve('Center zipper',[(0,-.231,.56),(0,-.27,.82),(0,-.274,1.07),(0,-.248,1.32),(0,-.216,1.49)],.009,amber,'Chest')
curve('Zipper tape left',[(-.018,-.239,.57),(-.018,-.28,.92),(-.018,-.256,1.31),(-.018,-.224,1.47)],.009,rib,'Chest')
for i in range(24):
    z=.63+i*.032
    y=-.285 if .77<z<1.23 else -.262
    sphere('Small zipper tooth',(0,y,z),(.013,.004,.004),amber,'Chest',12,8)
sphere('Zipper pull',(0,-.249,1.40),(.018,.014,.040),frames,'Chest',20,12)
# Minimal geometric badge, deliberately not a text logo.
for i in range(3):
    curve('Orange badge slash',[(.335+i*.033,-.212,1.35),(.35+i*.033,-.214,1.395)],.006,orange,'Chest')
curve('Chest pocket seam',[(-.46,-.199,1.30),(-.29,-.256,1.285),(-.23,-.258,1.293)],.004,rib,'Chest')

# Continuous head topology. Front is negative Y. No photo texture and no facial hair.
head_rows=[(1.91,.095,.11,-.021),(1.945,.157,.164,-.012),(2.00,.213,.198,0),
 (2.10,.254,.221,.005),(2.20,.275,.236,.018),(2.31,.278,.243,.03),
 (2.42,.272,.236,.044),(2.53,.248,.216,.06),(2.62,.191,.168,.073),
 (2.68,.10,.09,.075),(2.70,.015,.015,.075)]
verts=[];N=96
for z,rx,ry,cy in head_rows:
    for j in range(N):
        a=2*math.pi*j/N;x=rx*math.cos(a);y=cy+ry*math.sin(a)
        front=max(0,-math.sin(a))**5
        # A soft facial plane, rounded cheekbones and integrated mouth volume.
        y-=front*(.027*math.exp(-((abs(x)-.14)/.10)**2-((z-2.17)/.11)**2)
                   +.021*math.exp(-(x/.14)**2-((z-2.035)/.075)**2))
        verts.append((x,y,z))
faces=[]
for r in range(len(head_rows)-1):
    for j in range(N):
        a=r*N+j;b=r*N+(j+1)%N;faces.append((a,b,b+N,a+N))
faces.append(tuple(range(N-1,-1,-1)));faces.append(tuple((len(head_rows)-1)*N+j for j in range(N)))
mesh('Sculpted clean-shaven face',verts,faces,skin,'Head',2)
for side in (-1,1):
    ear=sphere('Ear', (side*.272,.022,2.217),(.055,.050,.094),skin)
    sphere('Ear inner', (side*.303,-.014,2.216),(.023,.014,.054),skin_shadow)
    curve('Ear rim',[(side*.303,-.008,2.164),(side*.319,-.016,2.204),(side*.316,-.01,2.255),(side*.30,.003,2.273)],.009,skin)

# Nose sculpt: bridge and soft tip integrated by a smooth loft, not a sphere stack.
rows=[(2.12,.029,-.269,.027),(2.14,.054,-.283,.037),(2.166,.053,-.306,.035),
      (2.195,.033,-.312,.041),(2.25,.028,-.272,.036),(2.31,.022,-.238,.026),(2.34,.014,-.222,.013)]
nvs=[]
for z,rx,cy,ry in rows:
    for j in range(48):a=2*math.pi*j/48;nvs.append((rx*math.cos(a),cy+ry*math.sin(a),z))
nfs=[]
for i in range(len(rows)-1):
    for j in range(48):a=i*48+j;b=i*48+(j+1)%48;nfs.append((a,b,b+48,a+48))
mesh('Nose sculpt',nvs,nfs,skin,'Head',2)
for side in (-1,1):
    sphere('Nostril hint',(side*.034,-.309,2.142),(.011,.005,.006),skin_shadow,segments=20,rings=12)

# Calm expression with a restrained, friendly smile.
curve('Upper lip',[(-.081,-.228,2.063),(-.038,-.247,2.072),(0,-.25,2.067),(.038,-.247,2.072),(.081,-.228,2.063)],.011,lip)
curve('Smile',[(-.085,-.231,2.068),(-.041,-.258,2.057),(0,-.262,2.054),(.041,-.258,2.057),(.085,-.231,2.068)],.0045,mouth)
curve('Lower lip',[(-.061,-.237,2.047),(0,-.255,2.037),(.061,-.237,2.047)],.011,lip)

# Expressive but restrained eyes. A bone per eye creates an exported geometric blink.
for side,label in [(-1,'L'),(1,'R')]:
    x=side*.124
    sphere('Eye white '+label,(x,-.216,2.286),(.081,.036,.043),white,'Eye.'+label,32,20)
    sphere('Iris '+label,(x+side*.001,-.249,2.286),(.030,.009,.032),iris,'Eye.'+label,28,18)
    sphere('Pupil '+label,(x+side*.001,-.257,2.286),(.017,.004,.022),pupil,'Eye.'+label,24,16)
    sphere('Catchlight '+label,(x-.009,-.261,2.297),(.007,.003,.008),glint,'Eye.'+label,16,10)
    curve('Upper eyelid '+label,[(x-.078,-.221,2.283),(x-.045,-.25,2.319),(x,-.252,2.326),(x+.047,-.248,2.315),(x+.078,-.218,2.286)],.008,skin)
    curve('Lower eyelid '+label,[(x-.074,-.221,2.279),(x,-.252,2.248),(x+.074,-.219,2.28)],.0055,skin_shadow)
    curve('Eyebrow '+label,[(x-.078,-.217,2.389,.45),(x-.037,-.231,2.405,1),(x+.017,-.229,2.40,1),(x+.077,-.201,2.379,.30)],.016,hair)

# Slim geometric glasses, a distinctive style feature, with no opaque lens surfaces.
for side in (-1,1):
    cx=side*.126;z=2.288
    pts=[(cx-.095,-.281,z+.061),(cx-.07,-.288,z+.083),(cx+.069,-.288,z+.083),
         (cx+.096,-.281,z+.060),(cx+.095,-.286,z-.055),(cx+.070,-.29,z-.082),
         (cx-.068,-.29,z-.082),(cx-.095,-.283,z-.055)]
    curve('Glasses rim',pts,.006,frames,closed=True)
    curve('Glasses temple',[(side*.224,-.279,2.325),(side*.272,-.19,2.324),(side*.29,.038,2.313),(side*.288,.075,2.26)],.006,frames)
curve('Glasses bridge',[(-.030,-.291,2.32),(0,-.308,2.334),(.030,-.291,2.32)],.0058,frames)

# Custom swept hair cap with a natural asymmetric hairline and individual sculpted locks.
vs=[];rings=18;segs=96
for i in range(rings+1):
    t=i/rings
    for j in range(segs):
        a=2*math.pi*j/segs
        # Longer back/sides, lifted front with a side part.
        front=max(0,-math.sin(a)); side=math.cos(a)
        lower=2.28+.205*front+.025*side*front
        z=lower+(2.772-lower)*math.sin(t*math.pi/2)
        width=.295*math.cos(t*math.pi/2)
        depth=.26*math.cos(t*math.pi/2)
        x=width*math.cos(a)-.018*math.sin(t*math.pi)
        y=.066+depth*math.sin(a)
        vs.append((x,y,z))
fs=[]
for i in range(rings):
    for j in range(segs):a=i*segs+j;b=i*segs+(j+1)%segs;fs.append((a,b,b+segs,a+segs))
mesh('Swept hair cap',vs,fs,hair,'Head',1)
for i in range(12):
    t=i/11
    pts=[(.205-.035*t,-.167+.06*t,2.51+.045*t,.20),
         (.103-.055*t,-.213+.04*t,2.637+.060*t,1.0),
         (-.055-.07*t,-.182+.053*t,2.747+.027*math.sin(t*3),1.05),
         (-.235-.015*t,-.072+.094*t,2.672-.06*t,.65),
         (-.273,.06+.04*t,2.53-.13*t,.08)]
    curve('Sculpted swept lock %02d'%i,pts,.022 if i%3 else .026,hair if i%3 else hair_high,res=5)
for side in (-1,1):
    for i in range(5):
        curve('Side hair groove',[(side*.279,-.052+i*.025,2.43+i*.016,.1),
              (side*.288,.015+i*.02,2.50+i*.023,.65),(side*.233,.12+i*.014,2.59+i*.024,.1)],.008,hair_high)

# Convert all curves and subdivision results to portable mesh data before skin binding.
for o in parts:
    bpy.context.view_layer.objects.active=o;o.select_set(True)
    for x in bpy.context.selected_objects:
        if x!=o:x.select_set(False)
    if o.type=='CURVE':bpy.ops.object.convert(target='MESH')
    for m in list(o.modifiers):
        if m.type=='SUBSURF':bpy.ops.object.modifier_apply(modifier=m.name)
    o.select_set(False)

# One articulated skeleton, exported with three named reusable animation clips.
bpy.ops.object.armature_add(enter_editmode=True,location=(0,0,0))
rig=bpy.context.object;rig.name='AM_Hero_Rig';arm=rig.data;arm.name='AM_Hero_Skeleton'
arm.edit_bones.remove(arm.edit_bones[0])
def bone(name,head,tail,parent=None):
    b=arm.edit_bones.new(name);b.head=head;b.tail=tail
    if parent:b.parent=arm.edit_bones[parent]
    return b
bone('Root',(0,0,.45),(0,0,.65))
bone('Chest',(0,0,1.0),(0,0,1.65),'Root')
bone('Head',(0,.02,1.85),(0,.02,2.45),'Chest')
bone('Eye.L',(-.124,-.22,2.286),(-.124,-.22,2.35),'Head')
bone('Eye.R',(.124,-.22,2.286),(.124,-.22,2.35),'Head')
bpy.ops.object.mode_set(mode='OBJECT')
for o in parts:
    group=o.vertex_groups.new(name=o['bind_bone']);group.add(list(range(len(o.data.vertices))),1.0,'REPLACE')
    mod=o.modifiers.new('Avatar skin','ARMATURE');mod.object=rig
    o.parent=rig
for p in rig.pose.bones:p.rotation_mode='XYZ'

scene=bpy.context.scene;scene.render.fps=30
def reset_pose():
    for p in rig.pose.bones:p.location=(0,0,0);p.rotation_euler=(0,0,0);p.scale=(1,1,1)
def key_pose(frame):
    for p in rig.pose.bones:
        p.keyframe_insert('location',frame=frame,group=p.name)
        p.keyframe_insert('rotation_euler',frame=frame,group=p.name)
        p.keyframe_insert('scale',frame=frame,group=p.name)
def blink(t,centers):
    value=1
    for center in centers:
        d=abs(t-center)
        if d<.12:value=min(value,.045+.955*d/.12)
    return value
def make_clip(name,seconds,pose):
    rig.animation_data_create();rig.animation_data.action=None
    act=bpy.data.actions.new(name);rig.animation_data.action=act
    length=round(seconds*30)
    for frame in range(1,length+2):
        reset_pose();pose((frame-1)/30,seconds);key_pose(frame)
    act.use_fake_user=True
    rig.animation_data.action=None
    track=rig.animation_data.nla_tracks.new();track.name=name
    strip=track.strips.new(name,1,act);strip.name=name
    track.mute=True
    return act
def idle(t,d):
    phase=math.sin(2*math.pi*t/d)
    rig.pose.bones['Chest'].scale=(1+.004*phase,1+.009*phase,1+.004*phase)
    rig.pose.bones['Head'].rotation_euler=(math.radians(.7)*phase,math.radians(.6)*phase,math.radians(1.7)*phase)
    for n in ('Eye.L','Eye.R'):rig.pose.bones[n].scale=(1,blink(t,[1.45,4.8]),1)
def welcome(t,d):
    s=math.sin(math.pi*t/d)**2
    rig.pose.bones['Chest'].rotation_euler[2]=math.radians(-3)*s
    rig.pose.bones['Head'].rotation_euler=(math.radians(6)*math.sin(2*math.pi*t/d)*s,math.radians(-3)*s,math.radians(7)*s)
    for n in ('Eye.L','Eye.R'):rig.pose.bones[n].scale=(1,blink(t,[.9]),1)
def look(t,d):
    s=math.sin(2*math.pi*t/d)
    rig.pose.bones['Head'].rotation_euler=(math.radians(-1)*math.sin(math.pi*t/d),0,math.radians(12)*s)
    for n in ('Eye.L','Eye.R'):rig.pose.bones[n].scale=(1,blink(t,[2.0]),1)
idle_action=make_clip('Idle',6,idle)
welcome_action=make_clip('Welcome',2.4,welcome)
look_action=make_clip('LookAround',4,look)
reset_pose();rig.animation_data.action=None

# Export only the model and skeleton, keeping studio equipment out of the asset.
bpy.ops.object.select_all(action='DESELECT');rig.select_set(True)
for o in parts:o.select_set(True)
bpy.context.view_layer.objects.active=rig
scene.frame_set(1)
export_args=dict(filepath=str(OUT/'am-hero-avatar.glb'),export_format='GLB',use_selection=True,
                 export_animations=True,export_animation_mode='NLA_TRACKS',export_nla_strips=True,
                 export_skins=True,export_morph=False,export_yup=True,export_cameras=False,export_lights=False)
bpy.ops.export_scene.gltf(**export_args)

# A studio rig for previews; the asset itself remains background-free.
world=bpy.data.worlds.new('Warm charcoal studio') if not scene.world else scene.world
scene.world=world;world.use_nodes=True
world.node_tree.nodes['Background'].inputs[0].default_value=(*rgb('#8C8175'),1)
world.node_tree.nodes['Background'].inputs[1].default_value=.22
def area(name,loc,power,color,size,target=(0,0,1.8)):
    bpy.ops.object.light_add(type='AREA',location=loc);o=bpy.context.object;o.name=name
    o.data.energy=power;o.data.color=rgb(color);o.data.shape='DISK';o.data.size=size
    o.rotation_euler=(Vector(target)-o.location).to_track_quat('-Z','Y').to_euler()
area('Key / large softbox',(-3,-4,5),650,'#FFF3DF',4)
area('Fill / soft neutral',(3,-2,3),430,'#F8F8F8',3)
area('Orange rim',(-2,2,3.4),850,'#F9542A',2.4)
area('Hair strip',(1,1,5),700,'#D9835A',2.3)
bpy.ops.object.camera_add(location=(3.0,-7.5,3.05))
camera=bpy.context.object;camera.name='Portrait camera'
target=Vector((0,0,1.64));camera.rotation_euler=(target-camera.location).to_track_quat('-Z','Y').to_euler()
camera.data.type='ORTHO';camera.data.ortho_scale=2.8;scene.camera=camera
scene.render.engine='CYCLES';scene.cycles.samples=40;scene.cycles.use_denoising=True
scene.render.resolution_x=1000;scene.render.resolution_y=1000;scene.render.resolution_percentage=100
scene.render.image_settings.file_format='PNG';scene.render.image_settings.color_mode='RGBA'
scene.render.film_transparent=True
scene.view_settings.view_transform='AgX'
rig.animation_data.action=idle_action
scene.frame_start=1;scene.frame_end=181;scene.frame_set(1)
bpy.ops.wm.save_as_mainfile(filepath=str(OUT/'am-hero-avatar.blend'))
scene.render.filepath=str(OUT/'am-hero-avatar-three-quarter.png');bpy.ops.render.render(write_still=True)
camera.location=(0,-8,2.8);camera.rotation_euler=(target-camera.location).to_track_quat('-Z','Y').to_euler()
scene.render.filepath=str(OUT/'am-hero-avatar-front.png');bpy.ops.render.render(write_still=True)
stats={'name':'AM / The Maker','style':'Original clean-shaven stylized clay character',
       'animations':{'Idle':6,'Welcome':2.4,'LookAround':4},'fps':30,
       'mesh_objects':len(parts),'vertices':sum(len(o.data.vertices) for o in parts),
       'triangles':sum(sum(len(p.vertices)-2 for p in o.data.polygons) for o in parts),
       'source':'Original procedural geometry; no third-party model or photo textures.',
       'asset_scope':'Upper-body bust; animated head, torso and geometric eye blink. No hand-wave clip.',
       'glb_bytes':(OUT/'am-hero-avatar.glb').stat().st_size}
(OUT/'avatar-manifest.json').write_text(json.dumps(stats,indent=2),encoding='utf-8')
print('AVATAR_BUILD_COMPLETE '+json.dumps(stats))
